/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package calportlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Event service. Represents a row in the &quot;AcademicEvents_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link calportlet.model.impl.EventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link calportlet.model.impl.EventImpl}.
 * </p>
 *
 * @author robert
 * @see Event
 * @see calportlet.model.impl.EventImpl
 * @see calportlet.model.impl.EventModelImpl
 * @generated
 */
public interface EventModel extends BaseModel<Event> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event model instance should use the {@link Event} interface instead.
	 */

	/**
	 * Returns the primary key of this event.
	 *
	 * @return the primary key of this event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event.
	 *
	 * @param primaryKey the primary key of this event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event ID of this event.
	 *
	 * @return the event ID of this event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event.
	 *
	 * @param eventId the event ID of this event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the name_hu of this event.
	 *
	 * @return the name_hu of this event
	 */
	@AutoEscape
	public String getName_hu();

	/**
	 * Sets the name_hu of this event.
	 *
	 * @param name_hu the name_hu of this event
	 */
	public void setName_hu(String name_hu);

	/**
	 * Returns the name_en of this event.
	 *
	 * @return the name_en of this event
	 */
	@AutoEscape
	public String getName_en();

	/**
	 * Sets the name_en of this event.
	 *
	 * @param name_en the name_en of this event
	 */
	public void setName_en(String name_en);

	/**
	 * Returns the event date of this event.
	 *
	 * @return the event date of this event
	 */
	public Date getEventDate();

	/**
	 * Sets the event date of this event.
	 *
	 * @param eventDate the event date of this event
	 */
	public void setEventDate(Date eventDate);

	/**
	 * Returns the tvsz of this event.
	 *
	 * @return the tvsz of this event
	 */
	@AutoEscape
	public String getTvsz();

	/**
	 * Sets the tvsz of this event.
	 *
	 * @param tvsz the tvsz of this event
	 */
	public void setTvsz(String tvsz);

	/**
	 * Returns the typeof event of this event.
	 *
	 * @return the typeof event of this event
	 */
	public long getTypeofEvent();

	/**
	 * Sets the typeof event of this event.
	 *
	 * @param typeofEvent the typeof event of this event
	 */
	public void setTypeofEvent(long typeofEvent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Event event);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Event> toCacheModel();

	@Override
	public Event toEscapedModel();

	@Override
	public Event toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}